### PR TITLE
Nitant-Test find & Fix Bugs

### LINKED ISSUE #147: [PE-D][Tester C] Github field accepted values
The github parameter does not accept symbolic characters, although it is not specified in the help message. Consider adding these limits into the error message

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: lulucopter/ped#4

### LINKED ISSUE #153: [PE-D][Tester C] Find git
Find command does not work for git search if it includes the `@` as displayed.

Although labelled as severe, it feels like a featureflaw bug, since it works if the `@` is removed. 

First time users may search with the @ character since that is how it is displayed, so it can help if you filter that out of your find predicates (since its not a valid input anyway) or if you make it clear in the documentation

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: lulucopter/ped#5

### LINKED ISSUE #156: [PE-D][Tester E] ALL search for module and tag fields does not work as specified.
Executing `find m/all/CS5242` does not return any contacts even though there are matching contacts in the database.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tantzeyeong/ped#2

### LINKED ISSUE #157: [PE-D][Tester C] find by type: accepts invalid command formats
The command does not throw an error as expected when invalid command formats are included, eg. `find typ/stu/` or `find typ//`.

In fact, since there are only `stu prof ta` types, the command should throw an error if other string values are input into the command. 
Users may mistakenly type `find typ/student` and that displays 0 persons listed.

Throwing as error on what input values are accepted will definitely make the user experience better, esp if they don't have to dig into the UG for the exact accepted type values

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lulucopter/ped#6

### LINKED ISSUE #161: [PE-D][Tester E] No error checking for "Type search" feature.
No error checking / error message given when invalid type for "Type search" feature is given. Executing `find typ/profs` returns empty list with no errors.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tantzeyeong/ped#3

### PR DESCRIPTION
**Pull request by nitant-p**
This PR adds test for `FindCommand`, `FindCommandParser` and the `PersonMatchesPredicate` class.

It also fixes the following bugs:

Fixes #157 #161 
image

Fixes #156 

Input: `find m/all/CS5242`

image

The UI also does not display the GitHub username with `@` so this fixes #153. 

Update GitHub username message constraints to fix #147 

image

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -49,9 +51,12 @@ public FindCommand parse(String args) throws ParseException {
                 PREFIX_EMAIL, PREFIX_GENDER, PREFIX_TAG, PREFIX_LOCATION, PREFIX_TYPE, PREFIX_GITHUBUSERNAME,
                 PREFIX_RATING, PREFIX_SPECIALISATION, PREFIX_YEAR, PREFIX_OFFICEHOUR);
 
-        if (!(areAllArgsValid(PREFIX_NAME, PREFIX_MODULE_CODE, PREFIX_PHONE, PREFIX_EMAIL,
+        if (!(areAllArgsNonEmpty(PREFIX_NAME, PREFIX_MODULE_CODE, PREFIX_PHONE, PREFIX_EMAIL,
                 PREFIX_GENDER, PREFIX_TAG, PREFIX_LOCATION, PREFIX_TYPE, PREFIX_GITHUBUSERNAME,
                 PREFIX_RATING, PREFIX_SPECIALISATION, PREFIX_YEAR, PREFIX_OFFICEHOUR))) {
+            if (hasEmptyFields) {
```
Comment (Jonaspng) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Why do you need this additional if statement. Is it redundant?

**Review by Jonaspng — APPROVED** [review]
LGTM.

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java (hunk 1 above)
Comment (nitant-p) [reply src/main/java/seedu/address/logic/parser/FindCommandParser.java]: It's not redundant, but the method `areAllArgsNonEmpty` now has a misleading name and its implementation looks strange. I will change it.

`areAllArgsNonEmpty` is supposed to check if at least one field has been specified, and then after that, `hasEmptyFields` is supposed to check if any of the fields provided are empty.
